version: '3'
services:
  postgres:
    image: 'postgres:latest'
    container_name: 'chat-room'
    ports:
      - 5442:5432
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
